/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Disease;
import Business.DiseaseCatalog;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.DrugCatalog;
import Business.Validator;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author urvi
 */
public class ManageDiseaseCatalog extends javax.swing.JPanel {

    /**
     * Creates new form ManageDiseaseCatalog
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    public ManageDiseaseCatalog(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateDisease();
    }

    public void populateDisease(){
        DefaultTableModel model = (DefaultTableModel) tblDisease.getModel();

        model.setRowCount(0);
        for(Disease dc : system.getDiseasecatalog().getListOfDisease()) {
                Object[] row = new Object[1];
                row[0] = dc;
                model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisease = new javax.swing.JTable();
        btnDisease = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDisease = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDisease.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Disease Name"
            }
        ));
        jScrollPane1.setViewportView(tblDisease);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 390, 120));

        btnDisease.setBackground(new java.awt.Color(102, 204, 255));
        btnDisease.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnDisease.setText("Add Disease");
        btnDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiseaseActionPerformed(evt);
            }
        });
        add(btnDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Enter Disease Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        backJButton.setBackground(new java.awt.Color(102, 204, 255));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Manage Disease Catalog");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        txtDisease.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiseaseKeyPressed(evt);
            }
        });
        add(txtDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 114, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiseaseActionPerformed
        // TODO add your handling code here:
        try{
        if(txtDisease.getText().isEmpty() ) 
        JOptionPane.showMessageDialog(null,"Please fill all the data");
     else
     {
        
        String diseaseName = txtDisease.getText();
        Disease disease = system.getDiseasecatalog().addDisease();
        disease.setDisease_name(diseaseName);
        JOptionPane.showMessageDialog(null, "Disease Added to the catalog");
        populateDisease();
        
        txtDisease.setText("");
         }
        }
    
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Please enter correect fotmat of input");
        }
        
    }//GEN-LAST:event_btnDiseaseActionPerformed

    private void txtDiseaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiseaseKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtDisease);
    }//GEN-LAST:event_txtDiseaseKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnDisease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisease;
    private javax.swing.JTextField txtDisease;
    // End of variables declaration//GEN-END:variables
}
