/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Disease;
import Business.DiseaseCatalog;
import Business.Drug;
import Business.EcoSystem;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.DrugCatalog;
import Business.Validator;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author urvi
 */
public class ManageDrugCatalog extends javax.swing.JPanel {

    /**
     * Creates new form ManageDrugCatalog
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    public ManageDrugCatalog(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system; 
        populateDisease();
        populateDrug();
        txtAvail.setEnabled(false);
        txtDrug.setEnabled(false);
        txtPrice.setEnabled(false);
        chooseDate.setEnabled(false);
        boxDiseases.setEnabled(false);
        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(false);
                
    }

    public void populateDrug(){
        DefaultTableModel model = (DefaultTableModel) tblDrugs.getModel();

        model.setRowCount(0);
        for (Drug drug : system.getDrugCatalog().getListOfDrugs()) {
                Object[] row = new Object[5];
                row[0] = drug;
                row[1] = drug.getAvailability();
                row[2] = drug.getPrice();
                row[3] = drug.getExpiryDate();
                row[4] = drug.getDiseaseCured();

                model.addRow(row);
        } 
    }
    
    public void populateDisease(){
        for(Disease disease : system.getDiseasecatalog().getListOfDisease()){
            boxDiseases.addItem(disease.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAddNew = new javax.swing.JButton();
        txtDrug = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        txtAvail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        boxDiseases = new javax.swing.JComboBox<>();
        chooseDate = new com.toedter.calendar.JDateChooser();
        btnUpdateNew = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDrugs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Drug Name", "Availability", "Price", "Expiry Date", "Disease cured"
            }
        ));
        jScrollPane1.setViewportView(tblDrugs);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 60, 691, 124));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Manage Drug Catalog");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 20, -1, -1));

        btnAddNew.setBackground(new java.awt.Color(102, 204, 255));
        btnAddNew.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnAddNew.setText("Add New Drug");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });
        add(btnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 210, -1, -1));

        txtDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugActionPerformed(evt);
            }
        });
        txtDrug.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDrugKeyPressed(evt);
            }
        });
        add(txtDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 246, 180, -1));

        jLabel2.setFont(new java.awt.Font("Al Bayan", 1, 14)); // NOI18N
        jLabel2.setText("Enter Drug Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 248, -1, -1));

        backJButton.setBackground(new java.awt.Color(102, 204, 255));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 580, -1, -1));

        txtAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailActionPerformed(evt);
            }
        });
        txtAvail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAvailKeyPressed(evt);
            }
        });
        add(txtAvail, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 306, 180, -1));

        jLabel3.setFont(new java.awt.Font("Al Bayan", 1, 14)); // NOI18N
        jLabel3.setText("Availability:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 310, -1, -1));

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPriceKeyPressed(evt);
            }
        });
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 369, 180, -1));

        jLabel4.setFont(new java.awt.Font("Al Bayan", 1, 14)); // NOI18N
        jLabel4.setText("Manufacturing Price:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 373, -1, -1));

        jLabel5.setFont(new java.awt.Font("Al Bayan", 1, 14)); // NOI18N
        jLabel5.setText("Expiry Date:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 428, -1, -1));

        jLabel6.setFont(new java.awt.Font("Al Bayan", 1, 14)); // NOI18N
        jLabel6.setText("Disease Cured:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 489, -1, -1));

        add(boxDiseases, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 486, 180, -1));
        add(chooseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 428, 175, -1));

        btnUpdateNew.setBackground(new java.awt.Color(102, 204, 255));
        btnUpdateNew.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnUpdateNew.setText("Update Drug");
        btnUpdateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNewActionPerformed(evt);
            }
        });
        add(btnUpdateNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 210, -1, -1));

        btnAdd.setBackground(new java.awt.Color(102, 204, 255));
        btnAdd.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 531, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(102, 204, 255));
        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 531, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        txtAvail.setEnabled(true);
        txtDrug.setEnabled(true);
        txtPrice.setEnabled(true);
        chooseDate.setEnabled(true);
        boxDiseases.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnAddNew.setEnabled(false);
        btnUpdateNew.setEnabled(false);
        btnAdd.setEnabled(true);
        
        
        
        
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void txtDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDrugActionPerformed

    private void txtAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtAvailActionPerformed

    private void btnUpdateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugs.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row to update");
            return;
        }
        else{
            Drug dru = (Drug)tblDrugs.getValueAt(selectedRow,0);
            for(Drug d : system.getDrugCatalog().getListOfDrugs()){
                if(d.equals(dru)){
                    txtAvail.setEnabled(true);
                    txtDrug.setEnabled(false);
                    txtPrice.setEnabled(false);
                    chooseDate.setEnabled(true);
                    boxDiseases.setEnabled(false);
                    btnUpdate.setEnabled(true);
                    btnAddNew.setEnabled(false);
                    btnUpdateNew.setEnabled(false);
                    btnAdd.setEnabled(false);
                    txtDrug.setText(dru.getDrug_name());
                    //dru.setAvailability(Integer.valueOf(txtAvail.getText()));
                    txtPrice.setText(String.valueOf(dru.getPrice()));
                    //dru.setExpiryDate(chooseDate.getDate());
                    boxDiseases.setSelectedItem(dru.getDiseaseCured());
                    
                    
                }
            }
        }
        
        
    }//GEN-LAST:event_btnUpdateNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //Drug dru = (Drug)tblDrugs.getValueAt(selectedRow,0);
            for(Drug d : system.getDrugCatalog().getListOfDrugs()){
                if(d.getDrug_name().equals(txtDrug.getText())){
                    System.out.println("inside if hence found equal drug from table");
                    d.setAvailability(d.getAvailability()+Integer.valueOf(txtAvail.getText()));
                    d.setExpiryDate(chooseDate.getDate());
                    txtAvail.setEnabled(false);
                    txtDrug.setEnabled(false);
                    txtPrice.setEnabled(false);
                    chooseDate.setEnabled(false);
                    boxDiseases.setEnabled(false);
                    populateDrug();
                    btnAddNew.setEnabled(true);
                    btnUpdateNew.setEnabled(true);
                }
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
        if(txtDrug.getText().isEmpty() || txtAvail.getText().isEmpty() || txtPrice.getText().isEmpty()) 
        JOptionPane.showMessageDialog(null,"Please fill all the data");
     else
     {
        boolean check=false;
        for(Drug d : system.getDrugCatalog().getListOfDrugs()){
            if(d.equals(txtDrug.getText())){
                JOptionPane.showMessageDialog(null, "Drug Already exists, You can update it");
                check = true;
            }
        }
        if(!check){
                Drug drug = system.getDrugCatalog().addDrug();
                drug.setDrug_name(txtDrug.getText());
                drug.setAvailability(Integer.valueOf(txtAvail.getText()));
                drug.setPrice(Integer.valueOf(txtPrice.getText()));
                drug.setExpiryDate(chooseDate.getDate());
                drug.setDiseaseCured(boxDiseases.getSelectedItem().toString());
                
                populateDrug();
        
                JOptionPane.showMessageDialog(null, "Drug Successfully added");

                txtDrug.setText("");
                txtAvail.setText("");
                txtPrice.setText("");
                boxDiseases.setSelectedItem("");
                chooseDate.cleanup();
        }
               
                txtAvail.setEnabled(false);
                txtDrug.setEnabled(false);
                txtPrice.setEnabled(false);
                chooseDate.setEnabled(false);
                boxDiseases.setEnabled(false);
                btnUpdateNew.setEnabled(true);
                btnAddNew.setEnabled(true);
                }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Please enter correect fotmat of input");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtDrugKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDrugKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtDrug);
    }//GEN-LAST:event_txtDrugKeyPressed

    private void txtAvailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAvailKeyPressed
        // TODO add your handling code here:
        Validator.onlyInteger(evt, txtAvail);
    }//GEN-LAST:event_txtAvailKeyPressed

    private void txtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyPressed
        // TODO add your handling code here:
        Validator.onlyInteger(evt, txtPrice);
    }//GEN-LAST:event_txtPriceKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox<String> boxDiseases;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateNew;
    private com.toedter.calendar.JDateChooser chooseDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDrugs;
    private javax.swing.JTextField txtAvail;
    private javax.swing.JTextField txtDrug;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
