/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdmin;

import Business.Drug;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.PatientRole;
import Business.UserAccount.UserAccount;
import Business.Validator;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author urvi
 */
public class CreatePatientRecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientRecordJPanel
     */
    private Enterprise enterprise;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private EcoSystem business;
    private String filename;
    public CreatePatientRecordJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.business = business;
        panelDrug.setVisible(false);
        populateDetails();
        ButtonGroup group = new ButtonGroup();
            group.add(radioFemale);
            group.add(radioMale);
        ButtonGroup group1 = new ButtonGroup();
            group1.add(radioNo);
            group1.add(radioYes);
        ButtonGroup group2 = new ButtonGroup();
            group2.add(radioNoAffected);
            group2.add(radioYesAffected);    
    }
    
     public void populateDetails(){
       // txtFName.setText(person.getfName());
       // txtLName.setText(person.getlName());
      
       PatientRole dr = (PatientRole)userAccount.getRole();
       
       txtFname.setText(dr.getFname());
       txtLname.setText(dr.getLname());
       txtState.setText(dr.getState());
       dateDOB.setDate(dr.getDob());
       txtAddress.setText(dr.getAddress());
       txtCity.setText(dr.getCity());
       txtPhone.setText(dr.getPhone());
       boxDrug.setSelectedItem(dr.getPreviousAddictedDrug());
       String  gender=dr.getGender();
       if(gender!=null)
       {
       if(gender.equals("FEMALE"))
       {
           radioFemale.setSelected(true);
       }
       else
       {
           radioMale.setSelected(true);
       }
       }
       String rehab=dr.getRehab();
       String addid = dr.getAddicted();
       
       if(rehab!=null)
       {
           if(rehab.equals("Yes"))
       {
           radioYes.setSelected(true);
       }
       else
       {
           radioNo.setSelected(true);
       }
       }
       
       if(addid!=null)
       {
           if(addid.equals("Yes"))
       {
           radioYesAffected.setSelected(true);
       }
       else
       {
           radioNoAffected.setSelected(true);
       }
       }
       String path = dr.getImagePath();
       ImageIcon Image = new ImageIcon(path);
        lblPhoto.setIcon(Image);
    }
    public void populateCombo(){
        for(Drug drug : business.getDrugCatalog().getListOfDrugs()){
            boxDrug.addItem(drug.toString());
        }
    
        
    }
    
    public ImageIcon ResizeImage(String path){
    ImageIcon myImage=new ImageIcon(path);
    Image img=myImage.getImage();
    Image newImg=img.getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image=new ImageIcon(newImg);
    return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        radioFemale = new javax.swing.JRadioButton();
        radioMale = new javax.swing.JRadioButton();
        txtPhone = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        radioYes = new javax.swing.JRadioButton();
        radioNo = new javax.swing.JRadioButton();
        radioYesAffected = new javax.swing.JRadioButton();
        radioNoAffected = new javax.swing.JRadioButton();
        panelDrug = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        boxDrug = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dateDOB = new com.toedter.calendar.JDateChooser();
        btnUpload = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Create Patient Record");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 69, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/urvi/Desktop/People-Patient-Male-icon.png")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 53, 80, 70));

        jLabel3.setText("First Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 232, -1, -1));

        jLabel4.setText("Last Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 282, -1, -1));

        jLabel5.setText("Address:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 332, -1, -1));

        jLabel6.setText("City:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 392, -1, -1));

        jLabel7.setText("State:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 232, -1, -1));

        jLabel8.setText("Gender:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 282, -1, -1));

        jLabel9.setText("Date of Birth:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 390, -1, -1));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, -1));

        jLabel11.setText("Phone Number:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 339, -1, -1));

        jLabel12.setText("Have you visited Rehab Center before ? ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 516, -1, -1));

        jLabel13.setText("Have you being affected before?");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 562, -1, -1));

        jLabel10.setText("HEALTH DETAILS");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 453, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 153, 0));
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 436, 266, 22));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 481, 708, 10));

        jLabel14.setText("PERSONAL DETAILS");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 172, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 194, 708, 10));

        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFnameKeyPressed(evt);
            }
        });
        add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 231, 243, -1));

        txtLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLnameKeyPressed(evt);
            }
        });
        add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 278, 241, -1));

        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddressKeyPressed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 334, 241, -1));

        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCityKeyPressed(evt);
            }
        });
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 385, 241, -1));

        txtState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStateKeyPressed(evt);
            }
        });
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 231, 204, -1));

        radioFemale.setText("FEMALE");
        add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 279, 94, -1));

        radioMale.setText("MALE");
        add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 279, 84, -1));

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 334, 197, -1));

        lblPhoto.setText("UPLOAD PHOTO");
        lblPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 23, 127, 130));

        radioYes.setText("Yes");
        add(radioYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 509, 84, -1));

        radioNo.setText("No");
        add(radioNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 509, 94, -1));

        radioYesAffected.setText("Yes");
        radioYesAffected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioYesAffectedActionPerformed(evt);
            }
        });
        add(radioYesAffected, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 555, 84, -1));

        radioNoAffected.setText("No");
        add(radioNoAffected, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 555, 94, -1));

        panelDrug.setBackground(new java.awt.Color(255, 255, 255));
        panelDrug.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("DRUG DETAILS");
        panelDrug.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 0, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        panelDrug.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 28, 710, -1));

        jLabel22.setText("Drug Addicted to previously");
        panelDrug.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 62, -1, -1));

        panelDrug.add(boxDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 58, 148, -1));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setText("CREATE PATIENT RECORD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelDrug.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 103, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setText("DISCARD CHANGES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelDrug.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 103, 150, -1));

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setText("<<Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelDrug.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, -1, -1));

        add(panelDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 600, -1, -1));
        add(dateDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 390, 198, -1));

        btnUpload.setText("Upload Photo");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 159, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtAddress.setText("");
        txtCity.setText("");
        txtFname.setText("");
        txtLname.setText("");
        txtPhone.setText("");
        txtState.setText("");
        JOptionPane.showMessageDialog(null, "Changes Discarded");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        // TODO add your handling code here:
        //        if(userAccount.getRole().valPhone(txtPhone.getText()) == true) {
            //            txtPhone.setBackground(Color.yellow);
            //        } else {
            //            txtPhone.setBackground(Color.red);
            //        }
            Validator.onlyInteger(evt, txtPhone);
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
     {
     if (txtFname.getText().isEmpty() || txtLname.getText().isEmpty() || txtAddress.getText().isEmpty() || txtCity.getText().isEmpty() || txtState.getText().isEmpty() || txtPhone.getText().isEmpty() || boxDrug.getSelectedIndex()==-1)
            JOptionPane.showMessageDialog(null,"Please fill all the data");
     else
     {
       
        PatientRole pr = (PatientRole) userAccount.getRole();
        pr.setFname(txtFname.getText());
        pr.setLname(txtLname.getText());
        pr.setAddress(txtAddress.getText());
        pr.setCity(txtCity.getText());
        pr.setDob(dateDOB.getDate());
        pr.setState(txtState.getText());
        pr.setPhone(txtPhone.getText());
        //pr.setAddicted(false);

        //        if (userAccount.getRole().valPhone(txtPhone.getText())) {
            //            pr.setPhone(txtPhone.getText());
            //        } else {
            //            JOptionPane.showMessageDialog(null, "Please enter a valid Phone Number");
            //            txtPhone.setText("");
            //            return;
            //        }

        //        if(txtPhone.getBackground().equals(Color.red)){
            //            JOptionPane.showMessageDialog(null, "Please enter a valid Phone Number");
            //            txtPhone.setText("");
            //            return;
            //        }
        //        else if(txtPhone.getBackground().equals(Color.yellow)){
            //            pr.setPhone(txtPhone.getText());
            //        }

       if (radioFemale.isSelected() || radioMale.isSelected()) {
            if (radioFemale.isSelected()) {
                pr.setGender(radioFemale.getText());
            } else if (radioMale.isSelected()) {
                pr.setGender(radioMale.getText());
            }
        } 
     
     else {
            JOptionPane.showMessageDialog(null, "Please select Gender");
        }
        

        if (radioYes.isSelected() || radioNo.isSelected()) {
            if (radioYes.isSelected()) {
                pr.setRehab(radioYes.getText());
            } else if (radioNo.isSelected()) {
                pr.setRehab(radioNo.getText());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select if your have visited any Rahabilitation center ");
        }

        if (radioYesAffected.isSelected() || radioNoAffected.isSelected()) {
            if (radioYesAffected.isSelected()) {
                pr.setAddicted(radioYesAffected.getText());
                panelDrug.setVisible(true);
                populateCombo();
                pr.setPreviousAddictedDrug((String) boxDrug.getSelectedItem());

            } else if (radioNoAffected.isSelected()) {
                pr.setAddicted(radioNoAffected.getText());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select if you were being affected ever");
        }
        JOptionPane.showMessageDialog(null, "your profile is updated");
     }
    }
     
     catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Please enter correect fotmat of input");
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        file.showOpenDialog(null);
        File f=file.getSelectedFile();
        filename = f.getAbsolutePath();
        //pathTextField.setText(filename);
        lblPhoto.setIcon(ResizeImage(filename));
    }//GEN-LAST:event_btnUploadActionPerformed

    private void radioYesAffectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioYesAffectedActionPerformed
        // TODO add your handling code here:
        PatientRole pr = (PatientRole) userAccount.getRole();
        panelDrug.setVisible(true);
        populateCombo();
        pr.setPreviousAddictedDrug((String) boxDrug.getSelectedItem());
    }//GEN-LAST:event_radioYesAffectedActionPerformed

    private void txtFnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtFname);
    }//GEN-LAST:event_txtFnameKeyPressed

    private void txtLnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtLname);
    }//GEN-LAST:event_txtLnameKeyPressed

    private void txtAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtAddress);
    }//GEN-LAST:event_txtAddressKeyPressed

    private void txtCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtCity);
    }//GEN-LAST:event_txtCityKeyPressed

    private void txtStateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStateKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtState);
    }//GEN-LAST:event_txtStateKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDrug;
    private javax.swing.JButton btnUpload;
    private com.toedter.calendar.JDateChooser dateDOB;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JPanel panelDrug;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioNoAffected;
    private javax.swing.JRadioButton radioYes;
    private javax.swing.JRadioButton radioYesAffected;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables
}
