/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdmin;

import Business.Doctor.Doctor;
import Business.Doctor.DoctorDirectory;
import Business.EcoSystem;
import Business.Employee.Employee.Type;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Role.DoctorRole;
import Business.UserAccount.UserAccount;
import Business.Validator;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author urvi
 */
public class CreateDoctorRecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDoctorRecordJPanel
     */
   private JPanel userProcessContainer;
    private UserAccount account;
    private DoctorOrganization doctorOrganization;
    private EcoSystem business;
    private Doctor doctor;
    private String filename;
    public CreateDoctorRecordJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization doctorOrganization, EcoSystem business) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.doctorOrganization = (DoctorOrganization)doctorOrganization;
        populateDetails();
        ButtonGroup group = new ButtonGroup();
            group.add(radioFemale);
            group.add(radioMale);
        
       // docId.setText(String.valueOf(dr.getDoctorId()));
    }
    
    public void populateDetails(){
       // txtFName.setText(person.getfName());
       // txtLName.setText(person.getlName());
       DoctorRole dr = (DoctorRole) account.getRole();
       txtFname.setText(dr.getFname());
       txtLname.setText(dr.getLname());
       txtAge.setText(String.valueOf(dr.getAge()));
       dateDOB.setDate(dr.getDob());
       txtAddress.setText(dr.getAddress());
       txtCity.setText(dr.getCity());
       txtPhone.setText(dr.getPhone());
       boxBloodGroup.setSelectedItem(dr.getBloodGroup());
       boxMaritalStatus.setSelectedItem(dr.getMaritalStatus());
       boxSpc.setSelectedItem(dr.getSpecialization());
       String  gender=dr.getGender();
       if(gender!=null)
       {
       if(gender.equals("FEMALE"))
       {
           radioFemale.setSelected(true);
       }
       else
       {
           radioMale.setSelected(true);
       }
       }
       String path = dr.getImagePath();
       ImageIcon Image = new ImageIcon(path);
        lblPhoto.setIcon(Image);
    }
    
    public ImageIcon ResizeImage(String path){
    ImageIcon myImage=new ImageIcon(path);
    Image img=myImage.getImage();
    Image newImg=img.getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image=new ImageIcon(newImg);
    return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        boxSpc = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        boxBloodGroup = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        boxMaritalStatus = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        backBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        dateDOB = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        btnUpload = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel2.setText("Age");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel4.setText("Last Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel5.setText("Specialization");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel6.setText("Address");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        boxSpc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cancer", "Ortho", "Pysician", "opthal", "Cardiac" }));
        boxSpc.setSelectedIndex(-1);
        add(boxSpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 140, -1));

        jLabel7.setText("Gender");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel8.setText("Blood Group");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        boxBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "AB+", "AB-", "A+", "A-", "B+", "B-", "O+", "O-" }));
        add(boxBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 160, -1));

        jLabel9.setText("City");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jLabel10.setText("Marital Status");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jLabel11.setText("Phone Number");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, -1));

        boxMaritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Married", "Unmarried" }));
        add(boxMaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 160, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setText("Create Doctor Record");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        lblPhoto.setText("UPLOAD PHOTO");
        lblPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 127, 130));

        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/urvi/Desktop/People-Doctor-Male-icon.png")); // NOI18N
        jLabel13.setText("jLabel13");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel14.setText("Personal Details");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 140, -1));

        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFnameKeyPressed(evt);
            }
        });
        add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 140, -1));

        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCityKeyPressed(evt);
            }
        });
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 130, -1));

        txtLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLnameKeyPressed(evt);
            }
        });
        add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 160, -1));

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 160, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 430, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 580, -1));

        backBtn.setBackground(new java.awt.Color(102, 204, 255));
        backBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        createBtn.setBackground(new java.awt.Color(102, 204, 255));
        createBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        createBtn.setText("Save Doctor Record");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, -1));
        add(dateDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 160, -1));

        jLabel20.setText("Date of Birth:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 120, -1));

        jLabel21.setText("Date of Birth:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 276, -1, 30));

        radioMale.setText("MALE");
        add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        radioFemale.setText("FEMALE");
        add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        btnUpload.setText("Upload Photo");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
     try{
         
     if (txtFname.getText().isEmpty() || txtLname.getText().isEmpty() || txtAddress.getText().isEmpty() || txtCity.getText().isEmpty() || txtAge.getText().isEmpty() || txtPhone.getText().isEmpty() || boxBloodGroup.getSelectedIndex()==-1 || boxMaritalStatus.getSelectedIndex()==-1 || boxSpc.getSelectedIndex()==-1)
            JOptionPane.showMessageDialog(null,"Please fill all the data");
     else
     {
     //doctorOrganization.getDoctorDirectory().createDoctor(fname.getText(),boxSpc.getSelectedItem().toString());
     DoctorRole dr = (DoctorRole) account.getRole();
     dr.setFname(txtFname.getText());
     dr.setSpecialization((String)boxSpc.getSelectedItem());
     dr.setLname(txtLname.getText());
     dr.setAddress(txtAddress.getText());
     dr.setCity(txtCity.getText());
     dr.setDob(dateDOB.getDate());
     dr.setBloodGroup((String)boxBloodGroup.getSelectedItem());
     dr.setAge(Integer.parseInt(txtAge.getText()));
     dr.setPhone(txtPhone.getText());
     if(filename!=null)
     dr.setImagePath(filename);
     
//     if (account.getRole().valPhone(txtPhone.getText())) {
//            dr.setPhone(txtPhone.getText());
//        } else {
//            JOptionPane.showMessageDialog(null, "Please enter a valid Phone Number");
//            txtPhone.setText("");
//            return;
//        }
     
     if (radioFemale.isSelected() || radioMale.isSelected()) {
            if (radioFemale.isSelected()) {
                dr.setGender(radioFemale.getText());
            } else if (radioMale.isSelected()) {
                dr.setGender(radioMale.getText());
            }
        } 
     
     else {
            JOptionPane.showMessageDialog(null, "Please select Gender");
        }
     
     
     if(!boxBloodGroup.getSelectedItem().toString().equals("Select")){
         dr.setMaritalStatus(boxBloodGroup.getSelectedItem().toString());
     }
     else{
         JOptionPane.showMessageDialog(null, "Please select Blood group");
     }
     
     
     
     if(!boxMaritalStatus.getSelectedItem().toString().equals("Select")){
         dr.setMaritalStatus(boxMaritalStatus.getSelectedItem().toString());
     }
     else{
         JOptionPane.showMessageDialog(null, "PLease select Marital Status");
     }
     
     JOptionPane.showMessageDialog(null, "your profile is updated");
    }
     
     }
     catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Please enter correect fotmat of input");
        }
     
     
//     if(account.getEmployee().getFname().equals(fname.getText())){
//         
//     
//         Type.Doctor.getValue();
//     }   
//      DoctorDirectory dd = doctorOrganization.getDoctorDirectory();
//      Doctor dr = dd.createDoctor(fname.getText()); 
//      dr.setSpecialization((String)boxSpc.getSelectedItem());
     
    }//GEN-LAST:event_createBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        DoctorRole dr = (DoctorRole) account.getRole();
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        file.showOpenDialog(null);
        File f=file.getSelectedFile();
        filename = f.getAbsolutePath();
        //pathTextField.setText(filename);
        lblPhoto.setIcon(ResizeImage(filename));
        //dr.setImagePath(filename);
    }//GEN-LAST:event_btnUploadActionPerformed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
        Validator.onlyInteger(evt, txtAge);
    
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        // TODO add your handling code here:
        Validator.onlyInteger(evt, txtPhone);
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtFnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtFname);
    }//GEN-LAST:event_txtFnameKeyPressed

    private void txtLnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtLname);
    }//GEN-LAST:event_txtLnameKeyPressed

    private void txtCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtCity);
    }//GEN-LAST:event_txtCityKeyPressed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> boxBloodGroup;
    private javax.swing.JComboBox<String> boxMaritalStatus;
    private javax.swing.JComboBox<String> boxSpc;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton createBtn;
    private com.toedter.calendar.JDateChooser dateDOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
