/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdmin.Pharmacy;

import Business.Drug;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.Role.PharmacyManager;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.OrderMedicinesWorkRequest;
import Business.WorkQueue.WorkRequest;
import com.sun.javafx.css.Combinator;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.HospitalAdmin.Pharmacy.CompleteOrderJPanel;
import userinterface.HospitalAdmin.Pharmacy.ViewStockJPanel;

/**
 *
 * @author urvi
 */
public class CheckOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckOrdersJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private EcoSystem business;
    public CheckOrdersJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = (PharmacyOrganization)organization;
        populateOrders();
        
    }
    
    public void populateOrders(){
        DefaultTableModel model = (DefaultTableModel)tblOrderedDrugs.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){
            if(request instanceof OrderMedicinesWorkRequest){
            Object[] row = new Object[5];
            row[0] = (OrderMedicinesWorkRequest) request;
            row[1] = ((OrderMedicinesWorkRequest) request).getOrderedQuantity();
            row[3] = request.getSender().getEmployee().getFname();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getFname();
            row[4] = request.getStatus();
            
            model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderedDrugs = new javax.swing.JTable();
        btnComplete = new javax.swing.JButton();
        assignJButton = new javax.swing.JButton();
        btnViewStock = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Check Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        tblOrderedDrugs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Quantity", "Receiver", "Sender", "Order Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrderedDrugs);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 633, 192));

        btnComplete.setBackground(new java.awt.Color(102, 204, 255));
        btnComplete.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnComplete.setText("View Prescription>>");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });
        add(btnComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        assignJButton.setBackground(new java.awt.Color(102, 204, 255));
        assignJButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        btnViewStock.setBackground(new java.awt.Color(102, 204, 255));
        btnViewStock.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnViewStock.setText("View Stock");
        btnViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStockActionPerformed(evt);
            }
        });
        add(btnViewStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 150, -1));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 495, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrderedDrugs.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select an order to complete.");
            return;
        } else {
            OrderMedicinesWorkRequest request = (OrderMedicinesWorkRequest) tblOrderedDrugs.getValueAt(selectedRow, 0);
            if (request.getStatus().equals("Completed")) {
                JOptionPane.showMessageDialog(null, "The order is already completed.");

            }
            else if(request.getStatus().equals("Processing")){
                JOptionPane.showMessageDialog(null, "Please Assign first");
            }
            else {
                //OrderMedicinesWorkRequest req = (OrderMedicinesWorkRequest)tblOrderedDrugs.getValueAt(selectedRow, 0);
                PharmacyManager role = (PharmacyManager) account.getRole();
                for (Drug drug : role.getPharmacyDrugList().getListOfDrugs()) {
                    if (request.getDrugName().equals(drug.getDrug_name())) {
                        int available = drug.getAvailability();
                        System.out.println("availability"+available);
                        System.out.println("ordered"+request.getOrderedQuantity());
                        if (request.getOrderedQuantity() > available || available == 0) {
                            System.out.println("checked quantity done");
                            JOptionPane.showMessageDialog(null, "There is no enough stock to continue this order. Please wait");
                        } else {
                            request.setStatus("Processing");

                            CompleteOrderJPanel completeOrderJPanel = new CompleteOrderJPanel(userProcessContainer, account, request, business, organization);
                            userProcessContainer.add("completeOrderJPanel", completeOrderJPanel);
                            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                            layout.next(userProcessContainer);
                        }
                    }
                }

            }

        }
        
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = tblOrderedDrugs.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        WorkRequest request = (WorkRequest)tblOrderedDrugs.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Pending")){
            JOptionPane.showMessageDialog(null, "You cannot Assign twice.");
        }
        else if(request.getStatus().equals("Complete")){
            JOptionPane.showMessageDialog(null, "Order is already completed!");
        }
        else{
            request.setReceiver(account);
            request.setStatus("Pending");
            populateOrders();
        }

    }//GEN-LAST:event_assignJButtonActionPerformed

    private void btnViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStockActionPerformed
        // TODO add your handling code here:
        ViewStockJPanel viewStockJPanel = new ViewStockJPanel(userProcessContainer, account, organization, business);
        userProcessContainer.add("ViewStockJPanel", viewStockJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewStockActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnViewStock;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrderedDrugs;
    // End of variables declaration//GEN-END:variables
}
