/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.HospitalAdmin.DoctorRole;

import Business.Drug;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Role.PatientRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.Validator;
import Business.WorkQueue.AppointmentWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.PrescriptionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author urvi
 */

public class DiagnosePatientsJPanel extends javax.swing.JPanel {

    /** Creates new form DiagnosePatientsJPanel */
private JPanel userProcessContainer;
private DoctorOrganization organization;
private Enterprise enterprise;
private UserAccount duserAccount;
private UserAccount paccount;
private  EcoSystem  business; 
private AppointmentWorkRequest request;
    public DiagnosePatientsJPanel(JPanel userProcessContainer, UserAccount paccount, UserAccount duserAccount, DoctorOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.paccount = paccount;
        this.business=business;
        this.duserAccount = duserAccount;
        this.request=(AppointmentWorkRequest)request;
        txtPatient.setText(paccount.getEmployee().getFname());
        populateDrugCombo();
        txtMessage.setEnabled(false);
        txtPatient.setEnabled(false);
        txtQuantity.setEnabled(false);
        boxDrug.setEnabled(false);
        btnPrescribe.setEnabled(false);
        populateRequestTable();
    }
  
    public void populateDrugCombo(){
        for(Drug drug: business.getDrugCatalog().getListOfDrugs()){
            boxDrug.addItem(drug);
        }
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : duserAccount.getWorkQueue().getWorkRequestList()){
            if(request instanceof LabTestWorkRequest){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getReceiver();
            row[2] = request.getSender();
            String result = ((LabTestWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
            row[4] = ((LabTestWorkRequest) request).getTestPatient();
            
            model.addRow(row);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrescribe = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPatient = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        boxDrug = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        requestTestJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrescribe.setBackground(new java.awt.Color(102, 204, 255));
        btnPrescribe.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnPrescribe.setText("Prescribe!!");
        btnPrescribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescribeActionPerformed(evt);
            }
        });
        add(btnPrescribe, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Diagnose the Patient");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 240, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Message: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        txtMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMessageKeyPressed(evt);
            }
        });
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 180, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Patient Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 20));

        txtPatient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPatientKeyPressed(evt);
            }
        });
        add(txtPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 180, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Drug Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 20));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Quantity:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
        });
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 180, -1));

        add(boxDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 180, -1));

        btnBack.setBackground(new java.awt.Color(102, 204, 255));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        requestTestJButton.setBackground(new java.awt.Color(102, 204, 255));
        requestTestJButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        requestTestJButton.setText("Request Test>>");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 180, -1));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setText("Prescribe Drugs>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 210, 30));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Receiver", "Status", "Result", "Patient"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 480, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescribeActionPerformed
        try{
        if(txtMessage.getText().isEmpty() || txtQuantity.getText().isEmpty()) 
        JOptionPane.showMessageDialog(null,"Please fill all the data");
     else
     {
        
        String message = txtMessage.getText();
        
        
        PrescriptionWorkRequest request = new PrescriptionWorkRequest();
        request.setMessage(message);
        request.setSender(duserAccount);
        request.setReceiver(paccount);
        request.setStatus("Diagnosed");
        request.setPrescribedDrug(String.valueOf(boxDrug.getSelectedItem()));
        request.setPrescribedDrugQuantity(Integer.parseInt(txtQuantity.getText()));
            paccount.getWorkQueue().getWorkRequestList().add(request);
            duserAccount.getWorkQueue().getWorkRequestList().add(request);
        
                 JOptionPane.showMessageDialog(null, "Successfully diagnosed");
        }
        }
    
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Please enter correect fotmat of input");
        }

    }//GEN-LAST:event_btnPrescribeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestLabTestJPanel", new RequestLabTestJPanel(userProcessContainer, duserAccount, paccount,enterprise));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtMessage.setEnabled(true);
        txtPatient.setEnabled(true);
        txtQuantity.setEnabled(true);
        boxDrug.setEnabled(true);
        btnPrescribe.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPatientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtPatient);
    }//GEN-LAST:event_txtPatientKeyPressed

    private void txtMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessageKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtMessage);
    }//GEN-LAST:event_txtMessageKeyPressed

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        // TODO add your handling code here:
        Validator.onlyInteger(evt, txtQuantity);
    }//GEN-LAST:event_txtQuantityKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> boxDrug;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPrescribe;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtPatient;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables

}
