/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdmin.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ClinicOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Role.DoctorRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.HospitalAdmin.CreateDoctorRecordJPanel;

/**
 *
 * @author hetashavi
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
   
    private JPanel userProcessContainer;
    private UserAccount account;
    private DoctorOrganization doctorOrganization;
    private EcoSystem business;
    private Enterprise enterprise;
    

    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise=enterprise;
        this.doctorOrganization = (DoctorOrganization)organization;
        DoctorRole dr = (DoctorRole) account.getRole();
        name.setText(dr.getFname());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileBtn = new javax.swing.JButton();
        appointmentBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profileBtn.setBackground(new java.awt.Color(102, 204, 255));
        profileBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        profileBtn.setText("Set Profile");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 155, -1, -1));

        appointmentBtn.setBackground(new java.awt.Color(102, 204, 255));
        appointmentBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        appointmentBtn.setText("Manage Appointment");
        appointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentBtnActionPerformed(evt);
            }
        });
        add(appointmentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 236, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Manage Doctor Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 81, -1, -1));
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 18, 186, 57));
    }// </editor-fold>//GEN-END:initComponents

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        CreateDoctorRecordJPanel createDoctorRecordJPanel = new CreateDoctorRecordJPanel(userProcessContainer, account, doctorOrganization,business );
        userProcessContainer.add("CreateDoctorRecordJPanel", createDoctorRecordJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_profileBtnActionPerformed

    private void appointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentBtnActionPerformed
        // TODO add your handling code here:
        ManageAppointmentsJPanel manageAppointmentsJPanel = new ManageAppointmentsJPanel(userProcessContainer, account,doctorOrganization,enterprise,business);
        userProcessContainer.add("ManageAppointmentsJPanel", manageAppointmentsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_appointmentBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointmentBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JButton profileBtn;
    // End of variables declaration//GEN-END:variables
}
