/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */
package userinterface.CityWelfare;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.RehabOrganization;
import Business.Role.PatientRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RehabWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hetashavi
 */
public class RehabManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private RehabOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public RehabManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.business = business;
        this.organization = (RehabOrganization)organization;
        populateWorkQueueTable();
        //populateAvailable();
    }

    public void populateWorkQueueTable() {
        DefaultTableModel model = (DefaultTableModel) requestTable.getModel();

        model.setRowCount(0);

        
           for (WorkRequest request : account.getWorkQueue().getWorkRequestList()){
            if(request instanceof RehabWorkRequest){
            Object[] row = new Object[5];
            row[0] = request.getSender();
            row[1] = request.getReceiver();
            row[2] = request;
            UserAccount ua =request.getSender();
            if (ua.getRole() instanceof PatientRole) {
            PatientRole role = (PatientRole) ua.getRole();
//            for(Addicted ad : role.getAddictedDrugListObject().getListOfAddictedDrugs())
//            { 
//                if((ad.getAddictedDrug())!=null)
//                    row[3]=ad.getAddictedDrug();
//                //System.out.println(ad.getAddictedDrug());
//            }
            row[3] =((PatientRole) role).getPatientTag();
            row[4]=((RehabWorkRequest) request).getDrug();
            }
//            String result = ((RehabWorkRequest) request).getTestResult();
//            row[4] = result == null ? "Waiting" : result;
//            
            model.addRow(row);
            }
        }
            }
        

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        valueLabel1 = new javax.swing.JLabel();
        reqBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Welcome to Rehab Center");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 130, 20));
        add(valueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 130, 20));

        reqBtn.setBackground(new java.awt.Color(102, 204, 255));
        reqBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reqBtn.setText("Treat");
        reqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqBtnActionPerformed(evt);
            }
        });
        add(reqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 120, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Patient List");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 170, 30));

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Receiver", "Status", "Patient Tag", "Addicted Drug"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 500, 90));

        backJButton.setBackground(new java.awt.Color(102, 204, 255));
        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backJButton.setText("Refresh");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void reqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqBtnActionPerformed
        int selectedRow = requestTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row to assign the account", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            //SupplierWorkRequest p = (SupplierWorkRequest) requestTable.getValueAt(selectedRow, 2);
            WorkRequest request = (WorkRequest)requestTable.getValueAt(selectedRow, 2);
            request.setStatus("Treated");
            request.setReceiver(account);
            
            
            for (WorkRequest re : account.getWorkQueue().getWorkRequestList()){
            if(request instanceof RehabWorkRequest){
                UserAccount ua =request.getSender();
                if (ua.getRole() instanceof PatientRole) {
                PatientRole role = (PatientRole) ua.getRole();
            }
            }
            }
            JOptionPane.showMessageDialog(null, "Patient treated Successfully");
            populateWorkQueueTable();

        }
//        SupplierWorkRequest request= new SupplierWorkRequest();
//        request.setVaccine((Vaccine)comboVaccine.getSelectedItem());
//        request.setQuantity(Integer.parseInt(txtquant.getText()));
//        request.setStatus("Requested");
//        request.setSender(account);
//        //organization.getWorkQueue().getWorkRequestList().add(request);
//        s.getWorkQueue().getWorkRequestList().add(request);
//        populateWorkQueueTable();

    }//GEN-LAST:event_reqBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        new RehabManagerWorkAreaJPanel(userProcessContainer, account, organization, business, enterprise);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton reqBtn;
    private javax.swing.JTable requestTable;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel1;
    // End of variables declaration//GEN-END:variables

}
